"""Added password, phone_number, created_at columns under user

Revision ID: 2ea20b4e66d7
Revises: e8acf7b26662
Create Date: 2026-02-06 17:05:18.893514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ea20b4e66d7"
down_revision: Union[str, Sequence[str], None] = "e8acf7b26662"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
