"""Initial migration correct

Revision ID: c2811554bf3a
Revises: 964288ba9087
Create Date: 2026-02-02 20:21:38.218852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2811554bf3a'
down_revision: Union[str, Sequence[str], None] = '964288ba9087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('prompts',
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('constraints', sa.String(), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index(op.f('ix_prompts_prompt_id'), 'prompts', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompts_role'), 'prompts', ['role'], unique=False)
    op.create_index(op.f('ix_prompts_task'), 'prompts', ['task'], unique=False)
    op.create_index(op.f('ix_prompts_title'), 'prompts', ['title'], unique=False)
    op.create_table('structured_prompts',
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('structured_prompt', sa.String(), nullable=True),
    sa.Column('natural_prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('original_prompt_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['original_prompt_id'], ['prompts.prompt_id'], ),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index(op.f('ix_structured_prompts_prompt_id'), 'structured_prompts', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structured_prompts_prompt_id'), table_name='structured_prompts')
    op.drop_table('structured_prompts')
    op.drop_index(op.f('ix_prompts_title'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_task'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_role'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_prompt_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
